# -*- coding: utf-8 -*-
"""
Spyder Editor

This temporary script file is located here:
/home/jose/.spyder2/.temp.py
"""
import re
import os
import html.parser
import glob


def putingids(text):
    """
        It decodes the HTML entities and it deletes some anoying characters
    """
    text = re.sub(r'([^\w])(hombre que Tenía la mano paralizada)([^\w])', r'\1<rs key="org15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(María la madre de Jacobo y de José)([^\w])', r'\1<rs key="per59">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Señor del cielo y de la tierra)([^\w])', r'\1<rs key="per14">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Generación malvada y Adúltera)([^\w])', r'\1<rs key="org19">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(madre de los hijos de Zebedeo)([^\w])', r'\1<rs key="per41">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(venida del Hijo del Hombre)([^\w])', r'\1<rs key="tim2">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Espíritu de vuestro Padre)([^\w])', r'\1<rs key="per17">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(quien se complace mi alma)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(tiempo de la Regeneración)([^\w])', r'\1<rs key="tim2">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Príncipe de los demonios)([^\w])', r'\1<rs key="per20">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hombre rico de Arimatea)([^\w])', r'\1<rs key="per61">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(primer Día de la semana)([^\w])', r'\1<rs key="tim1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Abominación desoladora)([^\w])', r'\1<rs key="per20">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Días antes del diluvio)([^\w])', r'\1<rs key="tim4">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Hijo del Dios viviente)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ancianos del pueblo)([^\w])', r'\1<rs key="org25">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ciudad del Gran Rey)([^\w])', r'\1<rs key="pla3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Fundación del mundo)([^\w])', r'\1<rs key="tim3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Herodes el tetrarca)([^\w])', r'\1<rs key="per10">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hijo del carpintero)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(monte de los Olivos)([^\w])', r'\1<rs key="pla28">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(otro a la izquierda)([^\w])', r'\1<rs key="per56">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(principio del mundo)([^\w])', r'\1<rs key="tim3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(reino de los cielos)([^\w])', r'\1<rs key="pla19">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(tierra de Genesaret)([^\w])', r'\1<rs key="pla21">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Espíritus inmundos)([^\w])', r'\1<rs key="org6">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(cinco mil hombres)([^\w])', r'\1<rs key="org18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(cueva de ladrones)([^\w])', r'\1<rs key="pla30">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hijos del maligno)([^\w])', r'\1<rs key="org19">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hombre de poca fe)([^\w])', r'\1<rs key="per21">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(infierno de fuego)([^\w])', r'\1<rs key="pla15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(procurador Pilato)([^\w])', r'\1<rs key="per50">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(reino de mi Padre)([^\w])', r'\1<rs key="pla18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(reino de su Padre)([^\w])', r'\1<rs key="pla18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(rey de los Judíos)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(tropas de guardia)([^\w])', r'\1<rs key="org24">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(un lugar desierto)([^\w])', r'\1<rs key="pla43">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Espíritu de Dios)([^\w])', r'\1<rs key="per17">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Espíritu inmundo)([^\w])', r'\1<rs key="org6">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hombre de Cirene)([^\w])', r'\1<rs key="per54">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jesús de Nazaret)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jesús el galileo)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Juan el Bautista)([^\w])', r'\1<rs key="per18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(mudo endemoniado)([^\w])', r'\1<rs key="org6">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Señor del Sábado)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Simón el leproso)([^\w])', r'\1<rs key="per49">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(uno a la derecha)([^\w])', r'\1<rs key="per55">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ángel del Señor)([^\w])', r'\1<rs key="org4">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(doce Discípulos)([^\w])', r'\1<rs key="org3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(falsos profetas)([^\w])', r'\1<rs key="org14">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hija de Herodía)([^\w])', r'\1<rs key="per38">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hijo de Abraham)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Hijo del Hombre)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hijos del reino)([^\w])', r'\1<rs key="org18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Judas Iscariote)([^\w])', r'\1<rs key="per34">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(María Magdalena)([^\w])', r'\1<rs key="per58">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(once Discípulos)([^\w])', r'\1<rs key="org3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ovejas perdidas)([^\w])', r'\1<rs key="org13">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Padre celestial)([^\w])', r'\1<rs key="per14">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(aquella Región)([^\w])', r'\1<rs key="pla21">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Día del juicio)([^\w])', r'\1<rs key="tim2">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Dios de Israel)([^\w])', r'\1<rs key="per14">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(doce Apóstoles)([^\w])', r'\1<rs key="org3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Espíritu Santo)([^\w])', r'\1<rs key="per17">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(falsos cristos)([^\w])', r'\1<rs key="org23">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(horno de fuego)([^\w])', r'\1<rs key="pla15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(mar de Galilea)([^\w])', r'\1<rs key="pla7">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(profeta Daniel)([^\w])', r'\1<rs key="org8">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(sumo sacerdote)([^\w])', r'\1<rs key="per48">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(un endemoniado)([^\w])', r'\1<rs key="org6">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Dios viviente)([^\w])', r'\1<rs key="per14">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(fin del mundo)([^\w])', r'\1<rs key="tim2">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(propia ciudad)([^\w])', r'\1<rs key="pla8">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(reino de Dios)([^\w])', r'\1<rs key="pla19">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(rey de Israel)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ciego y mudo)([^\w])', r'\1<rs key="org15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(endemoniados)([^\w])', r'\1<rs key="org6">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hija de Sion)([^\w])', r'\1<rs key="pla3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Hijo de Dios)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(santa ciudad)([^\w])', r'\1<rs key="pla3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Días de Noé)([^\w])', r'\1<rs key="tim4">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(lugar santo)([^\w])', r'\1<rs key="pla30">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Discípulos)([^\w])', r'\1<rs key="per4">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Escrituras)([^\w])', r'\1<rs key="wor1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(estos doce)([^\w])', r'\1<rs key="org3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(gobernante)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(herodianos)([^\w])', r'\1<rs key="org9">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jesucristo)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Paralítico)([^\w])', r'\1<rs key="org15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(procurador)([^\w])', r'\1<rs key="per50">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(publicanos)([^\w])', r'\1<rs key="org20">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(sacerdotes)([^\w])', r'\1<rs key="org12">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(tercer Día)([^\w])', r'\1<rs key="tim1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Bartolomé)([^\w])', r'\1<rs key="per29">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Beelzebul)([^\w])', r'\1<rs key="per20">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Berequías)([^\w])', r'\1<rs key="per45">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Capernaúm)([^\w])', r'\1<rs key="pla11">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Centurión)([^\w])', r'\1<rs key="per57">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Decápolis)([^\w])', r'\1<rs key="pla40">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Discípulo)([^\w])', r'\1<rs key="org3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Espíritus)([^\w])', r'\1<rs key="org6">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Getsemaní)([^\w])', r'\1<rs key="pla32">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jerusalén)([^\w])', r'\1<rs key="pla3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(mensajero)([^\w])', r'\1<rs key="per18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(publicano)([^\w])', r'\1<rs key="org20">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(sacerdote)([^\w])', r'\1<rs key="org12">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(sinagogas)([^\w])', r'\1<rs key="pla47">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(tres Días)([^\w])', r'\1<rs key="tim1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Zorobabel)([^\w])', r'\1<rs key="per77">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ancianos)([^\w])', r'\1<rs key="org25">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Arimatea)([^\w])', r'\1<rs key="pla35">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Arquelao)([^\w])', r'\1<rs key="per62">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Barrabás)([^\w])', r'\1<rs key="per50">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Barrabás)([^\w])', r'\1<rs key="per51">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Betsaida)([^\w])', r'\1<rs key="pla45">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(demonios)([^\w])', r'\1<rs key="org6">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Eliaquim)([^\w])', r'\1<rs key="per79">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(enfermos)([^\w])', r'\1<rs key="org15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(escribas)([^\w])', r'\1<rs key="org5">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Espíritu)([^\w])', r'\1<rs key="per17">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Ezequías)([^\w])', r'\1<rs key="per71">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(fariseos)([^\w])', r'\1<rs key="org2">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(gentiles)([^\w])', r'\1<rs key="org16">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Gran Rey)([^\w])', r'\1<rs key="per14">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(guardias)([^\w])', r'\1<rs key="org24">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hermanas)([^\w])', r'\1<rs key="org11">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(infierno)([^\w])', r'\1<rs key="pla15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jeconías)([^\w])', r'\1<rs key="per75">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jeremías)([^\w])', r'\1<rs key="per15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(multitud)([^\w])', r'\1<rs key="org13">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(nazareno)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Pretorio)([^\w])', r'\1<rs key="pla37">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Profetas)([^\w])', r'\1<rs key="org8">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(profetas)([^\w])', r'\1<rs key="org8">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(saduceos)([^\w])', r'\1<rs key="org7">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Salatiel)([^\w])', r'\1<rs key="per76">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(sepulcro)([^\w])', r'\1<rs key="pla36">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(sinagoga)([^\w])', r'\1<rs key="pla47">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(soldados)([^\w])', r'\1<rs key="org24">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(tentador)([^\w])', r'\1<rs key="per20">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Zacarías)([^\w])', r'\1<rs key="per44">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Abraham)([^\w])', r'\1<rs key="per2">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Betania)([^\w])', r'\1<rs key="pla31">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Betfagé)([^\w])', r'\1<rs key="pla27">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Cadáver)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(criados)([^\w])', r'\1<rs key="org26">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(demonio)([^\w])', r'\1<rs key="org6">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Galilea)([^\w])', r'\1<rs key="pla7">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Gólgota)([^\w])', r'\1<rs key="pla34">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Gomorra)([^\w])', r'\1<rs key="pla17">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(guardia)([^\w])', r'\1<rs key="org24">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hermana)([^\w])', r'\1<rs key="org18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hermano)([^\w])', r'\1<rs key="org18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Herodes)([^\w])', r'\1<rs key="per10">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Herodía)([^\w])', r'\1<rs key="per37">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hombres)([^\w])', r'\1<rs key="org3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Josafat)([^\w])', r'\1<rs key="per66">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(leproso)([^\w])', r'\1<rs key="org15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Maestro)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Magdala)([^\w])', r'\1<rs key="pla38">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(una voz)([^\w])', r'\1<rs key="per14">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Zabulón)([^\w])', r'\1<rs key="pla12">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Zebedeo)([^\w])', r'\1<rs key="per24">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Andrés)([^\w])', r'\1<rs key="per22">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Caifás)([^\w])', r'\1<rs key="per48">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ciegos)([^\w])', r'\1<rs key="org15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(cielos)([^\w])', r'\1<rs key="pla18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Cirene)([^\w])', r'\1<rs key="pla33">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(cuerpo)([^\w])', r'\1<rs key="per25">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Daniel)([^\w])', r'\1<rs key="per46">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(diablo)([^\w])', r'\1<rs key="per20">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Hesrón)([^\w])', r'\1<rs key="per9">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Isaías)([^\w])', r'\1<rs key="per19">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jordán)([^\w])', r'\1<rs key="pla9">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Moisés)([^\w])', r'\1<rs key="per26">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Najsón)([^\w])', r'\1<rs key="per89">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Nínive)([^\w])', r'\1<rs key="pla20">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(nombre)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Pilato)([^\w])', r'\1<rs key="per50">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Raquel)([^\w])', r'\1<rs key="per16">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Roboam)([^\w])', r'\1<rs key="per63">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Salmón)([^\w])', r'\1<rs key="per90">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(siervo)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Abías)([^\w])', r'\1<rs key="per64">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Abiud)([^\w])', r'\1<rs key="per78">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(aguas)([^\w])', r'\1<rs key="pla43">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Alfeo)([^\w])', r'\1<rs key="per32">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(amado)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ángel)([^\w])', r'\1<rs key="org4">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Aquim)([^\w])', r'\1<rs key="per82">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Belén)([^\w])', r'\1<rs key="pla1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(César)([^\w])', r'\1<rs key="per42">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(cojos)([^\w])', r'\1<rs key="org15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(David)([^\w])', r'\1<rs key="per35">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Eliud)([^\w])', r'\1<rs key="per83">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Fares)([^\w])', r'\1<rs key="per7">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(gente)([^\w])', r'\1<rs key="org18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Hades)([^\w])', r'\1<rs key="pla15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jotam)([^\w])', r'\1<rs key="per69">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Judea)([^\w])', r'\1<rs key="pla2">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(magos)([^\w])', r'\1<rs key="org10">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(malos)([^\w])', r'\1<rs key="org19">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Mateo)([^\w])', r'\1<rs key="per27">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Rajab)([^\w])', r'\1<rs key="per91">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Sadoc)([^\w])', r'\1<rs key="per81">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Sidón)([^\w])', r'\1<rs key="pla23">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Siria)([^\w])', r'\1<rs key="pla14">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Tadeo)([^\w])', r'\1<rs key="per33">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Tamar)([^\w])', r'\1<rs key="per6">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Tomás)([^\w])', r'\1<rs key="per30">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Urías)([^\w])', r'\1<rs key="per96">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Uzías)([^\w])', r'\1<rs key="per68">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Zéraj)([^\w])', r'\1<rs key="per8">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Abel)([^\w])', r'\1<rs key="per43">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Acaz)([^\w])', r'\1<rs key="per70">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Amón)([^\w])', r'\1<rs key="per73">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Aram)([^\w])', r'\1<rs key="per87">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Azor)([^\w])', r'\1<rs key="per80">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Boaz)([^\w])', r'\1<rs key="per92">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(diez)([^\w])', r'\1<rs key="org3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Dios)([^\w])', r'\1<rs key="per14">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(doce)([^\w])', r'\1<rs key="org3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Hijo)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hijo)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Isaí)([^\w])', r'\1<rs key="per95">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(mudo)([^\w])', r'\1<rs key="org15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(niño)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Obed)([^\w])', r'\1<rs key="per94">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(País)([^\w])', r'\1<rs key="pla39">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Ramá)([^\w])', r'\1<rs key="pla6">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Sion)([^\w])', r'\1<rs key="pla29">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Tiro)([^\w])', r'\1<rs key="pla22">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Asa)([^\w])', r'\1<rs key="per65">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Ley)([^\w])', r'\1<rs key="wor1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ley)([^\w])', r'\1<rs key="wor1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(mar)([^\w])', r'\1<rs key="pla43">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Noé)([^\w])', r'\1<rs key="per47">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Rut)([^\w])', r'\1<rs key="per93">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ángeles)([^\w])', r'\1<rs key="org2">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ángeles)([^\w])', r'\1<rs key="org4">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(dos hermanos)([^\w])', r'\1<rs key="per21">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(dos hermanos)([^\w])', r'\1<rs key="per22">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(dos hermanos)([^\w])', r'\1<rs key="per23">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(dos hermanos)([^\w])', r'\1<rs key="per25">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(dos hijos de Zebedeo)([^\w])', r'\1<rs key="per22">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(dos hijos de Zebedeo)([^\w])', r'\1<rs key="per23">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(dos ladrones)([^\w])', r'\1<rs key="per55">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(dos ladrones)([^\w])', r'\1<rs key="per56">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hermanos)([^\w])', r'\1<rs key="org11">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hermanos)([^\w])', r'\1<rs key="org3">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hijos)([^\w])', r'\1<rs key="per23">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hijos)([^\w])', r'\1<rs key="per25">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(hombre)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jacob)([^\w])', r'\1<rs key="per4">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jacob)([^\w])', r'\1<rs key="per86">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jacobo)([^\w])', r'\1<rs key="per23">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jacobo)([^\w])', r'\1<rs key="per31">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jacobo)([^\w])', r'\1<rs key="per98">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jonás)([^\w])', r'\1<rs key="per36">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Jonás)([^\w])', r'\1<rs key="per40">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(José)([^\w])', r'\1<rs key="per12">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Judá)([^\w])', r'\1<rs key="pla2">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Judas)([^\w])', r'\1<rs key="per101">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Judas)([^\w])', r'\1<rs key="per34">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ladrones)([^\w])', r'\1<rs key="per55">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(ladrones)([^\w])', r'\1<rs key="per56">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(madre)([^\w])', r'\1<rs key="per41">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(María)([^\w])', r'\1<rs key="per11">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(María)([^\w])', r'\1<rs key="per59">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(muchas mujeres)([^\w])', r'\1<rs key="per41">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(muchas mujeres)([^\w])', r'\1<rs key="per58">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(muchas mujeres)([^\w])', r'\1<rs key="per59">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(mujer)([^\w])', r'\1<rs key="per58">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(multitud)([^\w])', r'\1<rs key="org18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(multitudes)([^\w])', r'\1<rs key="org13">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(multitudes)([^\w])', r'\1<rs key="org15">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(multitudes)([^\w])', r'\1<rs key="org18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Padre)([^\w])', r'\1<rs key="per14">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(padre)([^\w])', r'\1<rs key="per24">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(profeta)([^\w])', r'\1<rs key="org8">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(profeta)([^\w])', r'\1<rs key="per10">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(profeta)([^\w])', r'\1<rs key="per18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(pueblo)([^\w])', r'\1<rs key="org5">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(reino)([^\w])', r'\1<rs key="pla18">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(reino)([^\w])', r'\1<rs key="pla19">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Rey)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(rey)([^\w])', r'\1<rs key="per10">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Sábado)([^\w])', r'\1<rs key="tim9">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Sábados)([^\w])', r'\1<rs key="tim9">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Satanás)([^\w])', r'\1<rs key="per20">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Satanás)([^\w])', r'\1<rs key="per21">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Satanás)([^\w])', r'\1<rs key="pla20">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Señor)([^\w])', r'\1<rs key="per1">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Señor)([^\w])', r'\1<rs key="per14">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Señor)([^\w])', r'\1<rs key="per50">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Simón)([^\w])', r'\1<rs key="per100">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Simón)([^\w])', r'\1<rs key="per21">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(Simón)([^\w])', r'\1<rs key="per54">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(tierra)([^\w])', r'\1<rs key="pla41">\2</rs>\3', text, flags=re.MULTILINE)
    text = re.sub(r'([^\w])(tierra)([^\w])', r'\1<rs key="pla8">\2</rs>\3', text, flags=re.MULTILINE)
    return text



def main():
    i=1
    for doc in glob.glob("/home/jose/Dropbox/TEIBibel/juanTEI.xml"):
    
        # It takes the base name of the html file, it cuts its ending and keeps a new xml name
        basenamedoc = os.path.basename(doc)[:-3]  
        docFormatOut=basenamedoc+"xml"    
    
        with open(doc, "r", errors="replace", encoding="utf-8") as fin:
            content = fin.read()
    
        # it cleans the HTML from entities, etc        
        content=putingids(content)
        
     
            
            # It writes the result in the output folder
    
        with open (os.path.join("/home/jose/Dropbox/TEIBibel/output/", docFormatOut), "w", encoding="utf-8") as fout:
                fout.write(content)
        print(doc)
        print("Processed documents: ",i)
        i+=1

main()